"""Channel orchestrator — Slack/Telegram-driven multi-agent runner.

The orchestrator receives a single message ("dispatch") from a chat channel or
the dashboard, plans a small set of sub-agent tasks (using the configured
*planner* model — Claude by default, but never hardcoded), runs them in
parallel via :func:`server.ai_providers.execute_with_assignee`, and posts a
final aggregated reply back to the channel. Each sub-agent publishes
start/progress/done events to ``server.agent_bus`` so the frontend, the TUI
and other agents can subscribe to live progress.

Storage: ``~/.claude-dashboard-orchestrator.json`` — pure data, the orchestrator
itself contains *no* model names, channel ids, or routing rules in code.

::

    {
      "plannerAssignee":  "claude:opus",
      "aggregatorAssignee": "claude:sonnet",
      "defaultAssignees": ["claude:sonnet", "openai:gpt-4.1", "ollama:llama3.1"],
      "maxParallel":      4,
      "channelDebounceMs": 2000,
      "bindings": [
        { "kind": "slack",    "channel": "C0XXXXX", "workflowId": "wf_..." },
        { "kind": "telegram", "chat":    "-100123",  "assignees": ["claude:sonnet"] }
      ]
    }

A binding either points at a saved workflow (``workflowId``) — in which case
that workflow runs with the inbound message as ``extra_inputs.message`` — or
specifies which assignees to use for an ad-hoc plan. Bindings can be added
from the TUI, the dashboard UI, or directly via ``/api/orchestrator/bind``.
"""
from __future__ import annotations

import json
import os
import re
import threading
import time
import uuid
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any, Optional

from . import agent_bus
from .ai_providers import AIResponse, execute_with_assignee, get_registry
from .config import _env_path
from .logger import log
from .utils import _safe_read, _safe_write


ORCH_CONFIG_PATH = _env_path(
    "CLAUDE_DASHBOARD_ORCHESTRATOR",
    Path.home() / ".claude-dashboard-orchestrator.json",
)


# ───────── Defaults (env-overridable) ─────────

_DEFAULT_PLANNER     = os.environ.get("ORCH_PLANNER",     "claude:sonnet")
_DEFAULT_AGGREGATOR  = os.environ.get("ORCH_AGGREGATOR",  "claude:sonnet")
_DEFAULT_MAX_PARA    = int(os.environ.get("ORCH_MAX_PARALLEL", "4"))
_CHANNEL_DEBOUNCE_MS = int(os.environ.get("ORCH_DEBOUNCE_MS", "2000"))
_PER_AGENT_TIMEOUT_S = int(os.environ.get("ORCH_AGENT_TIMEOUT_S", "180"))

# E5 — per-agent isolated workspace root. Each binding gets its own subdir
# with a private CLAUDE.md so context from one channel doesn't leak into
# another. Disabled when the env var is unset.
_AGENT_WORKSPACE_ROOT = os.environ.get(
    "ORCH_AGENT_WORKSPACE_ROOT",
    str(Path.home() / ".claude-dashboard-agents"),
)


def _binding_id(binding: Optional[dict]) -> str:
    """Stable directory-safe id for a binding. ``slack:Cxxxxx`` etc.

    Path-traversal segments (``..``, ``/``, leading ``.``) are normalised so
    the result is always safe to splice into a path, even if the binding
    target was attacker-controlled.
    """
    if not binding:
        return ""
    kind = binding.get("kind", "")
    target = (binding.get("channel") or binding.get("chat") or "default")
    safe = re.sub(r"[^A-Za-z0-9_-]+", "_", f"{kind}-{target}")
    safe = safe.lstrip(".-_") or "default"
    return safe[:120]


def _ensure_workspace(binding: Optional[dict]) -> dict:
    """Materialise per-binding workspace if missing. Returns
    ``{"cwd": "...", "claudeMdPath": "..."}`` or ``{}`` when isolation is off
    or the binding has no id (e.g. http: default).
    """
    if not binding:
        return {}
    bid = _binding_id(binding)
    if not bid:
        return {}
    root = Path(_AGENT_WORKSPACE_ROOT) / bid
    try:
        root.mkdir(parents=True, exist_ok=True)
        memdir = root / "memory"
        memdir.mkdir(exist_ok=True)
        cmdpath = root / "CLAUDE.md"
        if not cmdpath.exists():
            label = binding.get("label") or bid
            seed = (
                f"# Orchestrator workspace — {label}\n\n"
                f"This file is auto-generated by the LazyClaude orchestrator "
                f"for the binding `{bid}`. Edit freely — nothing here is "
                f"overwritten on subsequent dispatches.\n\n"
                f"## Channel context\n"
                f"- kind: `{binding.get('kind')}`\n"
                f"- target: `{binding.get('channel') or binding.get('chat') or '—'}`\n"
                f"- assignees: {', '.join(binding.get('assignees') or [])}\n"
            )
            cmdpath.write_text(seed, encoding="utf-8")
        return {"cwd": str(root), "claudeMdPath": str(cmdpath)}
    except Exception as e:
        log.warning("workspace setup failed for %s: %s", bid, e)
        return {}


# ───────── Config ─────────

def _empty_cfg() -> dict:
    return {
        "plannerAssignee":     _DEFAULT_PLANNER,
        "aggregatorAssignee":  _DEFAULT_AGGREGATOR,
        "defaultAssignees":    [_DEFAULT_PLANNER],
        "maxParallel":         _DEFAULT_MAX_PARA,
        "channelDebounceMs":   _CHANNEL_DEBOUNCE_MS,
        "bindings":            [],
        "savedAt":             0,
    }


def load_config() -> dict:
    if not ORCH_CONFIG_PATH.exists():
        return _empty_cfg()
    try:
        data = json.loads(_safe_read(ORCH_CONFIG_PATH) or "{}")
        if not isinstance(data, dict):
            return _empty_cfg()
        cfg = _empty_cfg()
        cfg.update({
            "plannerAssignee":    str(data.get("plannerAssignee") or _DEFAULT_PLANNER),
            "aggregatorAssignee": str(data.get("aggregatorAssignee") or _DEFAULT_AGGREGATOR),
            "defaultAssignees":   [str(a) for a in (data.get("defaultAssignees") or []) if a]
                                  or [_DEFAULT_PLANNER],
            "maxParallel":        max(1, min(int(data.get("maxParallel") or _DEFAULT_MAX_PARA), 16)),
            "channelDebounceMs":  max(0, int(data.get("channelDebounceMs") or _CHANNEL_DEBOUNCE_MS)),
            "bindings":           [_sanitize_binding(b) for b in (data.get("bindings") or [])
                                   if isinstance(b, dict)],
            "savedAt":            int(data.get("savedAt") or 0),
        })
        cfg["bindings"] = [b for b in cfg["bindings"] if b]
        return cfg
    except Exception as e:
        log.warning("orch config load failed: %s", e)
        return _empty_cfg()


def _sanitize_binding(b: dict) -> Optional[dict]:
    kind = (b.get("kind") or "").strip().lower()
    if kind not in ("slack", "telegram", "discord", "email", "http"):
        return None
    out: dict = {"kind": kind}
    if kind == "slack":
        ch = (b.get("channel") or "").strip()
        if not ch:
            return None
        out["channel"] = ch
    elif kind == "telegram":
        chat = (b.get("chat") or "").strip()
        if not chat:
            return None
        out["chat"] = chat
    elif kind == "discord":
        ch = (b.get("channel") or "").strip()
        if not ch:
            return None
        out["channel"] = ch
    elif kind == "email":
        # SMTP config lives on the binding so different recipients can use
        # different relay/sender combinations. Required: smtp_host / user /
        # password / from / to. We never log password; never persist plaintext
        # other than the binding file (which is chmod 600 already).
        host = (b.get("smtp_host") or "").strip()
        smtp_user = (b.get("smtp_user") or "").strip()
        smtp_pwd = b.get("smtp_password") or ""
        sender = (b.get("from") or smtp_user).strip()
        to_field = b.get("to") or ""
        if not (host and smtp_user and smtp_pwd and sender and to_field):
            return None
        out["channel"] = sender   # use sender as the routing key
        out["smtp"] = {
            "smtp_host":     host,
            "smtp_port":     int(b.get("smtp_port") or 587),
            "smtp_user":     smtp_user,
            "smtp_password": smtp_pwd,
            "from":          sender,
            "to":            to_field,
        }
    else:  # http
        out["channel"] = (b.get("channel") or "default").strip()
    wf = (b.get("workflowId") or "").strip()
    if wf:
        out["workflowId"] = wf
    assignees = [str(a).strip() for a in (b.get("assignees") or []) if a]
    if assignees:
        out["assignees"] = assignees
    # v2.56.0 — per-binding fallback chain + daily budget cap (D6)
    fb = b.get("fallbackChain") or b.get("fallback") or []
    if isinstance(fb, list):
        clean_fb = [str(x).strip() for x in fb if str(x).strip()]
        if clean_fb:
            out["fallbackChain"] = clean_fb[:8]
    if "budgetUsdPerDay" in b:
        try:
            v = float(b["budgetUsdPerDay"])
            if v > 0:
                out["budgetUsdPerDay"] = round(v, 4)
        except (TypeError, ValueError):
            pass
    label = (b.get("label") or "").strip()
    if label:
        out["label"] = label
    # F2 (v2.58.0) — recurrence schedule. Single-shot 60s sweeper picks up
    # bindings whose ``schedule.everyMinutes`` has elapsed and dispatches
    # ``schedule.prompt`` against this binding. Both fields required to be
    # active; missing or malformed → ignored.
    sched = b.get("schedule")
    if isinstance(sched, dict):
        try:
            every = int(sched.get("everyMinutes") or 0)
            prompt = (sched.get("prompt") or "").strip()
        except (TypeError, ValueError):
            every, prompt = 0, ""
        if every >= 1 and prompt:
            out["schedule"] = {
                "everyMinutes": min(every, 7 * 24 * 60),    # cap 1 week
                "prompt":       prompt[:4000],
                "lastRunMs":    int(sched.get("lastRunMs") or 0),
            }
    return out


def save_config(cfg: dict) -> bool:
    cfg = {**cfg, "savedAt": int(time.time() * 1000)}
    return _safe_write(ORCH_CONFIG_PATH, json.dumps(cfg, ensure_ascii=False, indent=2))


def find_binding(kind: str, channel_or_chat: str) -> Optional[dict]:
    cfg = load_config()
    for b in cfg.get("bindings") or []:
        if b.get("kind") != kind:
            continue
        if kind == "slack" and b.get("channel") == channel_or_chat:
            return b
        if kind == "telegram" and b.get("chat") == channel_or_chat:
            return b
        if kind == "discord" and b.get("channel") == channel_or_chat:
            return b
        if kind == "email" and b.get("channel") == channel_or_chat:
            return b
        if kind == "http":
            return b
    return None


def _email_reply(smtp_cfg: dict, sender: str):
    from . import notify

    def _wire(text: str) -> None:
        try:
            r = notify.send_email(smtp_cfg, "Orchestrator reply",
                                   text[:38000])
            if not r.get("ok"):
                log.warning("email reply failed: %s", r.get("error"))
        except Exception as e:
            log.warning("email reply crash: %s", e)

    def _send(text: str) -> None:
        coalesced_reply("email", sender or "default", text, _wire)

    return _send


def dispatch_email(text: str, *, sender: str = "default", user: str = "") -> dict:
    """Convenience entry: dispatch with an email binding's smtp config wired
    as the reply sink. The binding for ``kind=email`` must already exist
    (``api_orch_bind`` with ``kind: 'email'``); ``sender`` is the routing key
    (typically the same address as ``from``).
    """
    binding = find_binding("email", sender)
    reply = None
    if binding and binding.get("smtp"):
        reply = _email_reply(binding["smtp"], sender)
    return dispatch(text, kind="email", channel=sender, user=user, reply=reply)


# ───────── Planner ─────────

_PLAN_FENCE_RE = re.compile(r"```(?:json)?\s*(\{.*?\})\s*```", re.DOTALL)
_PLAN_OBJ_RE = re.compile(r"(\{[\s\S]*\})")

# ── Plan LRU cache ─────────────────────────────────────────────────────
#
# Same user text on the same binding → same plan. We hash
# ``(text, binding-key, sorted assignees)`` and cache the parsed plan for
# ``_PLAN_CACHE_TTL_S`` seconds. A bounded LRU keeps memory in check.
#
# This is a pure latency win: the planner LLM call is by far the most
# expensive part of an ad-hoc dispatch, and many channels see repeated
# templated requests ("daily standup", "summarise PR ##").

import hashlib as _hashlib
from collections import OrderedDict as _OrderedDict

_PLAN_CACHE_SIZE = int(os.environ.get("ORCH_PLAN_CACHE_SIZE", "256"))
_PLAN_CACHE_TTL_S = int(os.environ.get("ORCH_PLAN_CACHE_TTL_S", "1800"))

_PLAN_CACHE: "_OrderedDict[str, tuple[float, list[dict]]]" = _OrderedDict()
_PLAN_CACHE_LOCK = threading.Lock()


def _plan_cache_key(text: str, binding: Optional[dict],
                    assignees: list[str]) -> str:
    bkey = ""
    if binding:
        bkey = (binding.get("kind", "") + "|"
                + (binding.get("channel") or binding.get("chat") or ""))
    blob = "\x1f".join([text.strip(), bkey] + sorted(assignees))
    return _hashlib.sha1(blob.encode("utf-8")).hexdigest()


def _plan_cache_get(key: str) -> Optional[list[dict]]:
    with _PLAN_CACHE_LOCK:
        item = _PLAN_CACHE.get(key)
        if item is None:
            return None
        ts, plan = item
        if time.time() - ts > _PLAN_CACHE_TTL_S:
            _PLAN_CACHE.pop(key, None)
            return None
        _PLAN_CACHE.move_to_end(key)
        return [dict(s) for s in plan]


def _plan_cache_set(key: str, plan: list[dict]) -> None:
    if not plan:
        return
    with _PLAN_CACHE_LOCK:
        _PLAN_CACHE[key] = (time.time(), [dict(s) for s in plan])
        _PLAN_CACHE.move_to_end(key)
        while len(_PLAN_CACHE) > _PLAN_CACHE_SIZE:
            _PLAN_CACHE.popitem(last=False)


def _plan_cache_clear_for_tests() -> None:
    with _PLAN_CACHE_LOCK:
        _PLAN_CACHE.clear()

_PLANNER_SYSTEM = """You are an orchestrator's planner. Break the user's request \
into 1-4 small parallel sub-tasks for sub-agents. Respond ONLY with a JSON object:
{"plan":[{"assignee":"<provider:model>","task":"<single-sentence prompt>"},...]}
Do not include any explanation. Choose assignees from the provided list."""


def _build_planner_prompt(user_text: str, available: list[str]) -> str:
    avail = ", ".join(available) or "claude:sonnet"
    return (f"Available assignees: {avail}\n"
            f"User request:\n{user_text.strip()}\n\n"
            f"Return JSON only.")


def _parse_plan(text: str, available: list[str]) -> list[dict]:
    """Best-effort plan extraction. Falls back to a single default-assignee step
    if the planner returned no parseable JSON. We never hardcode a model — the
    fallback uses the first entry of ``available``.
    """
    avail_set = set(available)
    candidates: list[str] = []
    m = _PLAN_FENCE_RE.search(text or "")
    if m:
        candidates.append(m.group(1))
    m2 = _PLAN_OBJ_RE.search(text or "")
    if m2:
        candidates.append(m2.group(1))
    candidates.append(text or "")
    for c in candidates:
        try:
            obj = json.loads(c)
        except Exception:
            continue
        plan = obj.get("plan") if isinstance(obj, dict) else None
        if not isinstance(plan, list):
            continue
        out: list[dict] = []
        for step in plan[:8]:
            if not isinstance(step, dict):
                continue
            a = str(step.get("assignee") or "").strip()
            t = str(step.get("task") or "").strip()
            if not t:
                continue
            if avail_set and a not in avail_set:
                a = available[0]
            out.append({"assignee": a or (available[0] if available else _DEFAULT_PLANNER),
                        "task": t})
        if out:
            return out
    # Fallback — just one task on the default assignee
    return [{"assignee": available[0] if available else _DEFAULT_PLANNER,
             "task": text.strip() or "Respond to the user."}]


# ───────── Run ─────────

# ───────── Coalesced channel reply (debounce per channel) ─────────
#
# Several sub-agents finish within milliseconds of each other and each
# wants to surface a status update. Without coalescing we burn N round
# trips to Slack/Telegram (and N quota slots). The debouncer maintains one
# pending buffer per ``(kind, channel)`` and one timer thread; further
# ``send()`` calls inside ``debounce_ms`` append to the buffer instead of
# opening a new HTTP call. When the timer fires, the joined text goes out
# in a single message.
#
# Optimization rationale:
# - One ``threading.Timer`` per active channel, started lazily.
# - Buffers cap at ``_COALESCE_MAX_CHARS`` to honour Slack's 39 KB / Telegram's
#   4 KB ceiling without truncating individual fragments mid-message.
# - Bypassed when ``debounce_ms <= 0`` (per-channel config knob) so existing
#   one-shot replies stay synchronous.

_COALESCE_MAX_CHARS = int(os.environ.get("ORCH_COALESCE_MAX", "30000"))


class _ReplyCoalescer:
    """Channel-keyed buffer + timer. Thread-safe."""

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._buf: dict[tuple[str, str], list[str]] = {}
        self._timers: dict[tuple[str, str], threading.Timer] = {}

    def schedule(self, key: tuple[str, str], text: str, debounce_ms: int,
                 sink) -> None:
        """``sink`` is ``Callable[[str], None]`` — the actual send-to-channel."""
        if debounce_ms <= 0:
            try:
                sink(text)
            except Exception as e:
                log.warning("coalesce immediate sink failed: %s", e)
            return
        with self._lock:
            buf = self._buf.setdefault(key, [])
            buf.append(text)
            # If the new fragment would push us past the cap, flush the
            # current buffer first (synchronously, cheap) and start fresh.
            if sum(len(x) for x in buf) > _COALESCE_MAX_CHARS:
                pending = self._buf.pop(key)
                t = self._timers.pop(key, None)
                if t is not None:
                    try:
                        t.cancel()
                    except Exception:
                        pass
                _flush_text = "\n".join(pending[:-1])
                self._buf[key] = [pending[-1]]
            else:
                _flush_text = ""
            existing = self._timers.get(key)
            if existing is None:
                timer = threading.Timer(debounce_ms / 1000.0,
                                        self._flush, args=(key, sink))
                timer.daemon = True
                self._timers[key] = timer
                timer.start()
        if _flush_text:
            try:
                sink(_flush_text)
            except Exception as e:
                log.warning("coalesce overflow sink failed: %s", e)

    def _flush(self, key: tuple[str, str], sink) -> None:
        with self._lock:
            buf = self._buf.pop(key, [])
            self._timers.pop(key, None)
        if not buf:
            return
        try:
            sink("\n".join(buf))
        except Exception as e:
            log.warning("coalesce timed sink failed: %s", e)

    def flush_now(self, key: Optional[tuple[str, str]] = None) -> None:
        """Force flush — for tests or shutdown."""
        with self._lock:
            keys = [key] if key else list(self._buf.keys())
            sinks: list[tuple[tuple[str, str], list[str]]] = []
            for k in keys:
                buf = self._buf.pop(k, [])
                t = self._timers.pop(k, None)
                if t is not None:
                    try:
                        t.cancel()
                    except Exception:
                        pass
                if buf:
                    sinks.append((k, buf))
        # Sinks are stored on the caller side, so flush_now() just clears.
        return None


_COALESCER = _ReplyCoalescer()


def coalesced_reply(kind: str, channel: str, text: str, sink,
                    debounce_ms: Optional[int] = None) -> None:
    """Public helper. ``sink(joined_text)`` is what actually hits the wire.

    The debounce window comes from the orchestrator config (``channelDebounceMs``)
    unless an explicit override is passed in.
    """
    if not text:
        return
    if debounce_ms is None:
        debounce_ms = load_config().get("channelDebounceMs", _CHANNEL_DEBOUNCE_MS)
    _COALESCER.schedule((kind, channel or ""), text, int(debounce_ms or 0), sink)


# ───────── Run history (SQLite) ─────────

_HISTORY_SCHEMA = """
CREATE TABLE IF NOT EXISTS orch_runs (
  run_id   TEXT PRIMARY KEY,
  ts       INTEGER NOT NULL,
  kind     TEXT NOT NULL,
  channel  TEXT NOT NULL DEFAULT '',
  user     TEXT NOT NULL DEFAULT '',
  via      TEXT NOT NULL DEFAULT 'ad-hoc',
  ok       INTEGER NOT NULL DEFAULT 1,
  error    TEXT,
  text     TEXT NOT NULL DEFAULT '',
  plan     TEXT NOT NULL DEFAULT '[]',
  results  TEXT NOT NULL DEFAULT '[]',
  final    TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_orch_runs_ts ON orch_runs(ts DESC);

-- F1 (v2.58.0) — NanoClaw-style inbound/outbound IPC tables. Each is a
-- single-writer log so a parallel debugger / replay tool can `tail` either
-- side without contending with the live orchestrator. The orch_runs table
-- above remains the rollup view; these two are the raw streams.
CREATE TABLE IF NOT EXISTS orch_inbound (
  id      INTEGER PRIMARY KEY AUTOINCREMENT,
  ts      INTEGER NOT NULL,
  run_id  TEXT NOT NULL,
  kind    TEXT NOT NULL,
  channel TEXT NOT NULL DEFAULT '',
  user    TEXT NOT NULL DEFAULT '',
  text    TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_orch_inbound_run ON orch_inbound(run_id);
CREATE INDEX IF NOT EXISTS idx_orch_inbound_chan_ts ON orch_inbound(kind, channel, ts DESC);

CREATE TABLE IF NOT EXISTS orch_outbound (
  id      INTEGER PRIMARY KEY AUTOINCREMENT,
  ts      INTEGER NOT NULL,
  run_id  TEXT NOT NULL,
  kind    TEXT NOT NULL,
  channel TEXT NOT NULL DEFAULT '',
  via     TEXT NOT NULL DEFAULT 'ad-hoc',
  ok      INTEGER NOT NULL DEFAULT 1,
  text    TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_orch_outbound_run ON orch_outbound(run_id);
CREATE INDEX IF NOT EXISTS idx_orch_outbound_chan_ts ON orch_outbound(kind, channel, ts DESC);
"""

_HISTORY_SCHEMA_READY = False


def _ensure_history_schema() -> None:
    global _HISTORY_SCHEMA_READY
    if _HISTORY_SCHEMA_READY:
        return
    from .db import _db, _db_init
    _db_init()
    with _db() as c:
        c.executescript(_HISTORY_SCHEMA)
    _HISTORY_SCHEMA_READY = True


def _persist_inbound(run_id: str, *, kind: str, channel: str, user: str,
                     text: str) -> None:
    """Append a single user → orchestrator message to ``orch_inbound``.

    Called at dispatch entry, *before* any planner work happens. Crashes after
    this point still leave a usable inbound log — useful when debugging "why
    did the orchestrator think the user said X?".
    """
    try:
        _ensure_history_schema()
        from .db import _db
        with _db() as c:
            c.execute(
                "INSERT INTO orch_inbound(ts, run_id, kind, channel, user, text)"
                " VALUES (?, ?, ?, ?, ?, ?)",
                (int(time.time() * 1000), run_id, kind, channel, user,
                 (text or "")[:16000]),
            )
    except Exception as e:
        log.warning("orch inbound persist failed: %s", e)


def _persist_outbound(run_id: str, *, kind: str, channel: str, via: str,
                      ok: bool, text: str) -> None:
    """Append a single orchestrator → channel reply to ``orch_outbound``.

    Called when the channel reply lands (or would land for ``http`` kind).
    Multiple rows per ``run_id`` are valid — coalesced replies still produce
    one row per actual wire send.
    """
    try:
        _ensure_history_schema()
        from .db import _db
        with _db() as c:
            c.execute(
                "INSERT INTO orch_outbound(ts, run_id, kind, channel, via, ok, text)"
                " VALUES (?, ?, ?, ?, ?, ?, ?)",
                (int(time.time() * 1000), run_id, kind, channel, via,
                 1 if ok else 0, (text or "")[:16000]),
            )
    except Exception as e:
        log.warning("orch outbound persist failed: %s", e)


def _persist_run_record(run_id: str, *, kind: str, channel: str, user: str,
                        text: str, plan: list, results: list, final: str,
                        via: str, ok: bool, error: Optional[str] = None) -> None:
    """Append a single dispatch outcome to ``orch_runs``. Best-effort: a
    persistence failure must not affect the channel reply we already produced.
    Also writes an outbound row mirroring the final reply text.
    """
    try:
        _ensure_history_schema()
        from .db import _db
        with _db() as c:
            c.execute(
                "INSERT OR REPLACE INTO orch_runs"
                "(run_id, ts, kind, channel, user, via, ok, error, text, plan, results, final)"
                " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                (run_id, int(time.time() * 1000), kind, channel, user, via,
                 1 if ok else 0, (error or None),
                 (text or "")[:8000],
                 json.dumps(plan, ensure_ascii=False)[:32000],
                 json.dumps(results, ensure_ascii=False)[:64000],
                 (final or "")[:32000]),
            )
    except Exception as e:
        log.warning("orch history persist failed: %s", e)
    # Mirror the final reply into the outbound stream — one row per dispatch.
    if (final or "").strip() or not ok:
        _persist_outbound(run_id, kind=kind, channel=channel, via=via,
                          ok=ok, text=(final or "(no reply)"))


def _spent_today_usd(kind: str, channel: str) -> float:
    """Sum of cost_usd from orch_runs results for ``(kind, channel)`` today.

    Cost is stored inside the results JSON (one entry per sub-agent). We
    extract via the SQLite ``json_extract`` function — fast even on big
    tables because we range-scan ``ts`` first via the index.
    """
    try:
        _ensure_history_schema()
        from .db import _db
        # Local-day rollover (UTC offset agnostic — treat ``today`` as
        # the last 24 hours for simplicity; users get a worst-case 24-hour
        # rolling cap rather than a midnight reset).
        cutoff_ms = int((time.time() - 86400) * 1000)
        with _db() as c:
            rows = c.execute(
                "SELECT results FROM orch_runs WHERE kind = ? AND channel = ? "
                "AND ts >= ? AND ok = 1",
                (kind, channel, cutoff_ms),
            ).fetchall()
        total = 0.0
        for r in rows:
            try:
                arr = json.loads(r["results"] or "[]")
                for it in arr:
                    cost = float((it or {}).get("cost_usd") or 0.0)
                    total += cost
            except Exception:
                continue
        return total
    except Exception as e:
        log.warning("orch _spent_today_usd failed: %s", e)
        return 0.0


def list_inbound(*, kind: str = "", channel: str = "",
                 limit: int = 100, since_id: int = 0) -> list[dict]:
    """Tail the user → orchestrator stream. Filters are exact-match; pass
    empty string to skip. ``since_id`` lets a cross-process tailer resume
    after a crash without re-reading rows.
    """
    try:
        _ensure_history_schema()
        from .db import _db
        clauses = ["id > ?"]
        params: list = [int(since_id or 0)]
        if kind:
            clauses.append("kind = ?"); params.append(kind)
        if channel:
            clauses.append("channel = ?"); params.append(channel)
        sql = ("SELECT id, ts, run_id, kind, channel, user, text "
               "FROM orch_inbound WHERE " + " AND ".join(clauses) +
               " ORDER BY id DESC LIMIT ?")
        params.append(max(1, min(int(limit), 1000)))
        with _db() as c:
            rows = c.execute(sql, params).fetchall()
        return [{"id": r["id"], "ts": r["ts"], "runId": r["run_id"],
                 "kind": r["kind"], "channel": r["channel"],
                 "user": r["user"], "text": r["text"]}
                for r in rows]
    except Exception as e:
        log.warning("orch list_inbound failed: %s", e)
        return []


def list_outbound(*, kind: str = "", channel: str = "",
                  run_id: str = "",
                  limit: int = 100, since_id: int = 0) -> list[dict]:
    """Tail the orchestrator → channel stream. Same filters as ``list_inbound``
    plus an optional ``run_id`` filter for "all replies for this dispatch"."""
    try:
        _ensure_history_schema()
        from .db import _db
        clauses = ["id > ?"]
        params: list = [int(since_id or 0)]
        if kind:
            clauses.append("kind = ?"); params.append(kind)
        if channel:
            clauses.append("channel = ?"); params.append(channel)
        if run_id:
            clauses.append("run_id = ?"); params.append(run_id)
        sql = ("SELECT id, ts, run_id, kind, channel, via, ok, text "
               "FROM orch_outbound WHERE " + " AND ".join(clauses) +
               " ORDER BY id DESC LIMIT ?")
        params.append(max(1, min(int(limit), 1000)))
        with _db() as c:
            rows = c.execute(sql, params).fetchall()
        return [{"id": r["id"], "ts": r["ts"], "runId": r["run_id"],
                 "kind": r["kind"], "channel": r["channel"],
                 "via": r["via"], "ok": bool(r["ok"]), "text": r["text"]}
                for r in rows]
    except Exception as e:
        log.warning("orch list_outbound failed: %s", e)
        return []


def list_run_history(limit: int = 50) -> list[dict]:
    try:
        _ensure_history_schema()
        from .db import _db
        with _db() as c:
            rows = c.execute(
                "SELECT run_id, ts, kind, channel, user, via, ok, error, text, final"
                " FROM orch_runs ORDER BY ts DESC, rowid DESC LIMIT ?",
                (max(1, min(int(limit), 500)),),
            ).fetchall()
        return [{"runId": r["run_id"], "ts": r["ts"], "kind": r["kind"],
                 "channel": r["channel"], "user": r["user"], "via": r["via"],
                 "ok": bool(r["ok"]), "error": r["error"],
                 "text": r["text"], "final": r["final"]} for r in rows]
    except Exception as e:
        log.warning("orch history list failed: %s", e)
        return []


def get_run_record(run_id: str) -> Optional[dict]:
    try:
        _ensure_history_schema()
        from .db import _db
        with _db() as c:
            r = c.execute("SELECT * FROM orch_runs WHERE run_id = ?",
                          (run_id,)).fetchone()
        if not r:
            return None
        return {
            "runId": r["run_id"], "ts": r["ts"], "kind": r["kind"],
            "channel": r["channel"], "user": r["user"], "via": r["via"],
            "ok": bool(r["ok"]), "error": r["error"],
            "text": r["text"], "final": r["final"],
            "plan": json.loads(r["plan"] or "[]"),
            "results": json.loads(r["results"] or "[]"),
        }
    except Exception as e:
        log.warning("orch history get failed: %s", e)
        return None


def _new_run_id() -> str:
    return uuid.uuid4().hex[:12]


def _topic(run_id: str, *parts: str) -> str:
    return ".".join(("orch", run_id, *parts))


def _execute_step(run_id: str, idx: int, assignee: str, task: str,
                  fallback_chain: Optional[list[str]] = None,
                  cwd: str = "") -> dict:
    """Execute one sub-agent task. If ``fallback_chain`` is non-empty and the
    primary assignee returns an error, walk the chain in order until one
    succeeds or all are exhausted. Each attempt publishes its own
    ``step.<idx>.try.<n>`` event so the live UI sees the failover decision.
    """
    chain: list[str] = [assignee]
    for fb in (fallback_chain or []):
        if fb and fb != assignee and fb not in chain:
            chain.append(fb)

    agent_bus.publish(_topic(run_id, f"step.{idx}.start"),
                      {"assignee": assignee, "task": task,
                       "fallbackChain": chain[1:]},
                      source=assignee)
    t0 = time.time()
    last_out: dict = {}
    for attempt, candidate in enumerate(chain):
        attempt_t0 = time.time()
        try:
            resp: AIResponse = execute_with_assignee(
                candidate, task, cwd=cwd,
                timeout=_PER_AGENT_TIMEOUT_S, fallback=True,
            )
            ok = (resp.status == "ok")
            last_out = {
                "ok":        ok,
                "assignee":  candidate,
                "task":      task,
                "output":    resp.output if ok else "",
                "error":     resp.error if not ok else "",
                "model":     resp.model,
                "provider":  resp.provider,
                "tokens":    resp.tokens_total,
                "cost_usd":  float(resp.cost_usd or 0.0),
                "durationMs": int((time.time() - attempt_t0) * 1000),
                "failoverIndex": attempt,
            }
        except Exception as e:
            last_out = {
                "ok": False, "assignee": candidate, "task": task,
                "output": "", "error": f"{type(e).__name__}: {e}",
                "cost_usd": 0.0,
                "durationMs": int((time.time() - attempt_t0) * 1000),
                "failoverIndex": attempt,
            }
        if last_out.get("ok"):
            break
        if attempt + 1 < len(chain):
            agent_bus.publish(_topic(run_id, f"step.{idx}.failover"),
                              {"failed": candidate, "next": chain[attempt + 1],
                               "error": last_out.get("error", "")},
                              source="orchestrator")
    last_out["totalDurationMs"] = int((time.time() - t0) * 1000)
    agent_bus.publish(_topic(run_id, f"step.{idx}.done"), last_out,
                      source=last_out.get("assignee", "?"))
    return last_out


def _aggregate(aggregator: str, user_text: str, results: list[dict]) -> str:
    """Ask a small model to merge sub-agent outputs. If aggregation itself
    fails, fall back to a deterministic concatenation — we never lie about
    success.
    """
    bullets = []
    for i, r in enumerate(results):
        head = f"#{i+1} {r['assignee']} ({'ok' if r['ok'] else 'err'})"
        body = r.get("output") or r.get("error") or ""
        bullets.append(f"{head}\n{body[:1500]}")
    joined = "\n\n".join(bullets)
    prompt = (
        f"User asked:\n{user_text.strip()}\n\n"
        f"Sub-agent results:\n{joined}\n\n"
        "Write a single concise reply to the user that synthesises the above. "
        "Do not invent facts; if results disagree, note the disagreement briefly."
    )
    try:
        resp = execute_with_assignee(aggregator, prompt, timeout=_PER_AGENT_TIMEOUT_S)
        if resp.status == "ok" and resp.output.strip():
            return resp.output.strip()
        log.warning("aggregator returned err: %s", resp.error)
    except Exception as e:
        log.warning("aggregator crash: %s", e)
    # Deterministic fallback — clearly labelled.
    return ("(aggregator unavailable — concatenated sub-agent outputs)\n\n"
            + "\n\n---\n\n".join(b for b in bullets))


def _run_workflow_binding(workflow_id: str, text: str, run_id: str,
                          user: str = "") -> dict:
    """Execute a saved workflow with the inbound message as input and block
    until completion. Returns ``{ok, final, runId, error}``.

    Lives next to ``dispatch()`` so the orchestrator owns its lifecycle and can
    publish bus events at every transition. We poll the workflow's run snapshot
    rather than reach into its internals — keeps the workflow engine
    untouched.
    """
    from . import workflows as wf

    agent_bus.publish(_topic(run_id, "workflow.start"),
                      {"workflowId": workflow_id, "text": text, "user": user},
                      source="orchestrator")
    start_resp = wf.api_workflow_run({"id": workflow_id})
    if not start_resp.get("ok"):
        err = str(start_resp.get("error") or "workflow start failed")
        agent_bus.publish(_topic(run_id, "workflow.error"),
                          {"error": err}, source="orchestrator")
        return {"ok": False, "error": err, "runId": run_id, "final": ""}

    wf_run_id = start_resp["runId"]
    deadline = time.time() + max(_PER_AGENT_TIMEOUT_S, 600)
    last_status = ""
    while time.time() < deadline:
        snap = wf._run_status_snapshot(wf_run_id)
        run = (snap or {}).get("run") or {}
        status = run.get("status") or ""
        if status != last_status:
            agent_bus.publish(_topic(run_id, "workflow.tick"),
                              {"status": status, "currentNodeId": run.get("currentNodeId"),
                               "iteration": run.get("iteration", 0)},
                              source="orchestrator")
            last_status = status
        if status in ("ok", "err"):
            results = run.get("nodeResults") or {}
            final_text = ""
            # Prefer an explicit output node, fall back to any node with a
            # non-empty output.
            for nid, r in results.items():
                if isinstance(r, dict) and r.get("output"):
                    final_text = r["output"]
            if status == "err":
                return {"ok": False, "error": run.get("error") or "workflow error",
                        "runId": run_id, "wfRunId": wf_run_id, "final": final_text}
            return {"ok": True, "final": final_text or "(workflow finished with no text)",
                    "runId": run_id, "wfRunId": wf_run_id}
        time.sleep(0.5)

    agent_bus.publish(_topic(run_id, "workflow.timeout"),
                      {"wfRunId": wf_run_id}, source="orchestrator")
    return {"ok": False, "error": "workflow timed out",
            "runId": run_id, "wfRunId": wf_run_id, "final": ""}


def dispatch(text: str, *, kind: str = "http", channel: str = "",
             user: str = "", reply: Optional[Any] = None) -> dict:
    """Run a single orchestrator turn for ``text``.

    ``kind`` ∈ {slack, telegram, http}. ``reply`` is an optional callable
    ``(text: str) -> None`` the caller passes in to deliver the final answer
    to the inbound channel; if absent, the caller can fetch the result from
    the return value or subscribe to ``orch.<run_id>.*`` on the agent bus.
    """
    text = (text or "").strip()
    if not text:
        return {"ok": False, "error": "empty text"}

    cfg = load_config()
    binding = find_binding(kind, channel) if channel else None
    run_id = _new_run_id()

    # ── Per-binding daily budget cap (D6) ───────────────────────────────
    # If the binding declared a USD/day cap, refuse new dispatches once
    # today's spend (sum of orch_runs.cost where channel matches) is over.
    # Cost figures come from sub-agent results — accumulated lazily, so we
    # query history rather than carrying a counter.
    if binding and binding.get("budgetUsdPerDay"):
        spent = _spent_today_usd(kind, channel)
        cap = float(binding["budgetUsdPerDay"])
        if spent >= cap:
            err_msg = (
                f"daily budget ${cap:.2f} reached for {kind}:{channel} "
                f"(spent ${spent:.2f} today). Try again tomorrow or raise "
                "the cap in the Orchestrator tab."
            )
            agent_bus.publish(_topic(run_id, "budget.exceeded"),
                              {"cap": cap, "spent": spent},
                              source="orchestrator")
            if callable(reply):
                try: reply(err_msg)
                except Exception: pass
            _persist_run_record(run_id, kind=kind, channel=channel, user=user,
                                text=text, plan=[], results=[],
                                final="", via="budget-blocked",
                                ok=False, error=err_msg)
            return {"ok": False, "runId": run_id, "error": err_msg,
                    "budgetCapUsd": cap, "spentTodayUsd": round(spent, 4)}

    # Determine assignee list for this dispatch — binding > config default.
    avail = list((binding or {}).get("assignees") or cfg["defaultAssignees"])
    avail = [a for a in avail if a]
    if not avail:
        avail = [cfg["plannerAssignee"]]

    # Inbound stream — F1 (v2.58.0). Persisted before any work so a crash
    # in the planner still leaves the user's request inspectable.
    _persist_inbound(run_id, kind=kind, channel=channel, user=user, text=text)

    agent_bus.publish(_topic(run_id, "begin"),
                      {"text": text, "kind": kind, "channel": channel,
                       "user": user, "available": avail,
                       "binding": binding},
                      source="orchestrator")

    # 0. Workflow-bound channel? Run the saved workflow instead of ad-hoc plan.
    if binding and binding.get("workflowId"):
        wf_result = _run_workflow_binding(
            binding["workflowId"], text, run_id, user=user,
        )
        agent_bus.publish(_topic(run_id, "final"),
                          {"text": wf_result.get("final", ""),
                           "via": "workflow",
                           "workflowId": binding["workflowId"],
                           "ok": wf_result.get("ok", False)},
                          source="orchestrator")
        if callable(reply):
            try:
                reply(wf_result.get("final") or
                      f"(workflow error: {wf_result.get('error', 'unknown')})")
            except Exception as e:
                log.warning("orch reply delivery failed: %s", e)
        _persist_run_record(run_id, kind=kind, channel=channel, user=user,
                            text=text, plan=[], results=[],
                            final=wf_result.get("final", ""),
                            via="workflow",
                            ok=wf_result.get("ok", False),
                            error=wf_result.get("error"))
        return {
            "ok": wf_result.get("ok", False),
            "runId": run_id,
            "via": "workflow",
            "workflowId": binding["workflowId"],
            "final": wf_result.get("final", ""),
            "error": wf_result.get("error"),
        }

    # 1. Plan — check LRU cache first (skip planner LLM call on repeats)
    planner = cfg["plannerAssignee"]
    cache_key = _plan_cache_key(text, binding, avail)
    cached_plan = _plan_cache_get(cache_key)
    if cached_plan is not None:
        plan = cached_plan
        agent_bus.publish(_topic(run_id, "plan"),
                          {"steps": plan, "cached": True},
                          source="orchestrator")
    else:
        try:
            plan_resp = execute_with_assignee(
                planner,
                _build_planner_prompt(text, avail),
                system_prompt=_PLANNER_SYSTEM,
                timeout=_PER_AGENT_TIMEOUT_S,
            )
            plan_text = plan_resp.output if plan_resp.status == "ok" else ""
        except Exception as e:
            log.warning("planner crash: %s", e)
            plan_text = ""
        plan = _parse_plan(plan_text, avail)
        _plan_cache_set(cache_key, plan)
        agent_bus.publish(_topic(run_id, "plan"),
                          {"steps": plan, "plannerOutput": plan_text[:2000],
                           "cached": False},
                          source=planner)

    # 2. Execute steps in parallel — with per-binding failover chain (D6)
    #    + per-binding isolated workspace (E5).
    pool_size = min(cfg["maxParallel"], max(1, len(plan)))
    results: list[dict] = [{} for _ in plan]
    binding_chain = (binding or {}).get("fallbackChain") or []
    workspace = _ensure_workspace(binding)
    step_cwd = workspace.get("cwd", "")
    with ThreadPoolExecutor(max_workers=pool_size, thread_name_prefix="orch") as pool:
        futs = {pool.submit(_execute_step, run_id, i,
                            step["assignee"], step["task"],
                            binding_chain, step_cwd): i
                for i, step in enumerate(plan)}
        for fut in as_completed(futs):
            idx = futs[fut]
            try:
                results[idx] = fut.result()
            except Exception as e:
                results[idx] = {"ok": False, "assignee": plan[idx]["assignee"],
                                "task": plan[idx]["task"], "error": str(e),
                                "output": "", "durationMs": 0}

    # 3. Aggregate
    final_text = _aggregate(cfg["aggregatorAssignee"], text, results)
    agent_bus.publish(_topic(run_id, "final"),
                      {"text": final_text, "results": results, "via": "ad-hoc"},
                      source=cfg["aggregatorAssignee"])

    # 4. Optional channel reply
    if callable(reply):
        try:
            reply(final_text)
        except Exception as e:
            log.warning("orch reply delivery failed: %s", e)

    _persist_run_record(run_id, kind=kind, channel=channel, user=user,
                        text=text, plan=plan, results=results,
                        final=final_text, via="ad-hoc", ok=True)

    return {
        "ok": True, "runId": run_id, "plan": plan,
        "results": results, "final": final_text,
    }


# ───────── Channel adapters ─────────

# Slack and Telegram both call into ``dispatch()`` via thin reply callbacks.
# Slack mode can be triggered either from the Events API webhook (registered
# as ``/api/slack/events`` in routes.py) or from a one-off dispatch.

def _slack_reply(channel: str, thread_ts: Optional[str] = None):
    from . import slack_api

    def _wire(text: str) -> None:
        try:
            payload = {"channel": channel, "text": text[:38000]}
            if thread_ts:
                payload["thread_ts"] = thread_ts
            slack_api._call("chat.postMessage", payload)
        except Exception as e:
            log.warning("slack reply failed: %s", e)

    def _send(text: str) -> None:
        coalesced_reply("slack", channel, text, _wire)

    return _send


def _discord_reply(channel: str):
    from . import discord_api

    def _wire(text: str) -> None:
        try:
            discord_api.send_message(channel, text)
        except Exception as e:
            log.warning("discord reply failed: %s", e)

    def _send(text: str) -> None:
        coalesced_reply("discord", channel, text, _wire)

    return _send


def handle_discord_interaction(payload: dict) -> dict:
    """Discord Interactions API receiver.

    Expects the payload Discord sends to the configured interactions endpoint.
    Returns a response dict that the HTTP handler serializes back to the
    client. Type-1 PING gets a Type-1 PONG; Type-2 application command + Type-3
    component / message events route into the orchestrator.
    """
    if not isinstance(payload, dict):
        return {"type": 4, "data": {"content": "(bad payload)"}}
    itype = payload.get("type")
    if itype == 1:                         # PING
        return {"type": 1}
    # Application command (slash) or component interaction
    chan = ((payload.get("channel") or {}).get("id")
            or payload.get("channel_id") or "")
    user = ((payload.get("member") or {}).get("user")
            or payload.get("user") or {}).get("username", "")
    text = ""
    data = payload.get("data") or {}
    # Slash command "/ask <prompt>" — pull the first string option
    for opt in (data.get("options") or []):
        if isinstance(opt, dict) and opt.get("type") == 3 and opt.get("value"):
            text = str(opt["value"]); break
    # Fall back to a raw "name + first option text" if shape differs
    if not text:
        text = str(data.get("custom_id") or data.get("name") or "").strip()

    if not (chan and text):
        return {"type": 4, "data": {"content": "(missing channel or text)"}}

    binding = find_binding("discord", str(chan))
    if binding is None and os.environ.get("ORCH_DISCORD_BIND_REQUIRED", "1") != "0":
        return {"type": 4, "data": {"content": "(channel not bound)"}}

    threading.Thread(
        target=dispatch,
        kwargs={"text": text, "kind": "discord", "channel": str(chan),
                "user": user, "reply": _discord_reply(str(chan))},
        name=f"orch-dc-{chan}",
        daemon=True,
    ).start()
    # Type 5 = "deferred channel message" — Discord shows a "thinking…" state
    # while the orchestrator runs. Final reply lands via send_message.
    return {"type": 5}


def _telegram_reply(chat: str, reply_to: Optional[int] = None):
    from . import telegram_api

    def _wire(text: str) -> None:
        try:
            telegram_api.send_message(chat, text, reply_to=reply_to)
        except Exception as e:
            log.warning("telegram reply failed: %s", e)

    def _send(text: str) -> None:
        coalesced_reply("telegram", chat, text, _wire)

    return _send


def handle_telegram_update(upd: dict) -> None:
    """Wire-up for telegram_api.start_long_poll(handler=this)."""
    msg = upd.get("message") or upd.get("edited_message") or {}
    chat = (msg.get("chat") or {}).get("id")
    if chat is None:
        return
    chat_str = str(chat)
    text = (msg.get("text") or "").strip()
    if not text:
        return
    binding = find_binding("telegram", chat_str)
    if binding is None:
        # Honour explicit-binding mode by default — silent if not bound.
        if os.environ.get("ORCH_TELEGRAM_BIND_REQUIRED", "1") != "0":
            return
    user = ((msg.get("from") or {}).get("username")
            or (msg.get("from") or {}).get("first_name") or "")
    threading.Thread(
        target=dispatch,
        kwargs={"text": text, "kind": "telegram", "channel": chat_str,
                "user": user,
                "reply": _telegram_reply(chat_str, reply_to=msg.get("message_id"))},
        name=f"orch-tg-{chat_str}",
        daemon=True,
    ).start()


def handle_slack_event(event: dict) -> None:
    """Wire-up for the Slack Events API webhook."""
    inner = event.get("event") or event
    if inner.get("type") not in ("app_mention", "message"):
        return
    if inner.get("subtype") in ("bot_message", "message_changed", "message_deleted"):
        return
    text = (inner.get("text") or "").strip()
    channel = (inner.get("channel") or "").strip()
    if not (text and channel):
        return
    binding = find_binding("slack", channel)
    if binding is None and os.environ.get("ORCH_SLACK_BIND_REQUIRED", "1") != "0":
        return
    user = inner.get("user") or ""
    thread_ts = inner.get("thread_ts") or inner.get("ts")
    threading.Thread(
        target=dispatch,
        kwargs={"text": text, "kind": "slack", "channel": channel, "user": user,
                "reply": _slack_reply(channel, thread_ts=thread_ts)},
        name=f"orch-sl-{channel}",
        daemon=True,
    ).start()


# ───────── Recurrence sweeper (F2) ─────────
#
# Single 60-second tick walks every binding with a non-empty
# ``schedule.everyMinutes``. Bindings whose ``lastRunMs`` is more than
# ``everyMinutes * 60_000`` ms ago get fired with their canned prompt.
# A successful fire updates ``lastRunMs`` back into the binding so the
# next tick computes the right delta.
#
# Why a single sweeper rather than per-binding Timers: bindings come and
# go, and Timer.cancel() races are easy to get wrong. One sweeper, one
# scan per tick, O(N_bindings) where N is small. Lock-free against
# dispatch since each fired dispatch runs in its own daemon thread.

_SWEEP_INTERVAL_S = max(5, int(os.environ.get("ORCH_SWEEP_INTERVAL_S", "60")))
_SWEEP_LOCK = threading.Lock()
_SWEEP_THREAD: Optional[threading.Thread] = None
_SWEEP_STOP = threading.Event()


def _sweep_once() -> int:
    """One pass over the bindings. Returns the number of dispatches fired
    (used by tests + status endpoints).
    """
    cfg = load_config()
    bindings = cfg.get("bindings") or []
    if not bindings:
        return 0
    now_ms = int(time.time() * 1000)
    fired = 0
    dirty = False
    for b in bindings:
        sched = b.get("schedule")
        if not (isinstance(sched, dict) and sched.get("everyMinutes")
                and sched.get("prompt")):
            continue
        every_ms = int(sched["everyMinutes"]) * 60_000
        last = int(sched.get("lastRunMs") or 0)
        if now_ms - last < every_ms:
            continue
        # Fire — in a daemon thread so a stuck dispatch doesn't block the
        # next tick.
        kind = b.get("kind", "")
        channel = b.get("channel") or b.get("chat") or "default"
        prompt = sched["prompt"]
        reply = None
        if kind == "slack":
            reply = _slack_reply(channel)
        elif kind == "telegram":
            reply = _telegram_reply(channel)
        elif kind == "discord":
            reply = _discord_reply(channel)
        elif kind == "email" and isinstance(b.get("smtp"), dict):
            reply = _email_reply(b["smtp"], b.get("channel", "default"))
        threading.Thread(
            target=dispatch,
            kwargs={"text": prompt, "kind": kind, "channel": channel,
                    "user": "scheduled", "reply": reply},
            name=f"orch-sweep-{kind}-{channel}",
            daemon=True,
        ).start()
        sched["lastRunMs"] = now_ms
        dirty = True
        fired += 1
    if dirty:
        save_config(cfg)
    return fired


def _sweep_loop() -> None:
    while not _SWEEP_STOP.is_set():
        try:
            _sweep_once()
        except Exception as e:
            log.warning("orch sweeper crash: %s", e)
        if _SWEEP_STOP.wait(_SWEEP_INTERVAL_S):
            return


def start_sweeper() -> bool:
    """Idempotent. Returns True if the sweeper was already running or just
    started, False on failure (currently always True).
    """
    global _SWEEP_THREAD
    with _SWEEP_LOCK:
        if _SWEEP_THREAD is not None and _SWEEP_THREAD.is_alive():
            return True
        _SWEEP_STOP.clear()
        t = threading.Thread(target=_sweep_loop, name="orch-sweeper",
                             daemon=True)
        _SWEEP_THREAD = t
        t.start()
    return True


def stop_sweeper(timeout: float = 2.0) -> None:
    global _SWEEP_THREAD
    with _SWEEP_LOCK:
        _SWEEP_STOP.set()
        t = _SWEEP_THREAD
        _SWEEP_THREAD = None
    if t is not None:
        t.join(timeout=timeout)


def start_listeners() -> dict:
    """Idempotently spin up Telegram long-poll if a token is configured.

    Slack inbound is webhook-driven (Slack Events API) — no listener needed
    here. Returns a small status dict so callers (server.py boot, /api/orch/start)
    can render the result.
    """
    from . import telegram_api
    started_tg = telegram_api.start_long_poll(handle_telegram_update)
    sweeper_ok = start_sweeper()
    return {
        "telegram": "running" if started_tg else "skipped (no token)",
        "slack":    "webhook-mode",
        "sweeper":  f"running (every {_SWEEP_INTERVAL_S}s)" if sweeper_ok else "off",
    }


# ───────── HTTP API ─────────

def api_orch_config_get(query: dict | None = None) -> dict:
    cfg = load_config()
    # Don't redact — there are no secrets here, only model names + channels.
    avail_providers = [p.provider_id for p in get_registry().available_providers()]
    return {"ok": True, "config": cfg, "availableProviders": avail_providers}


def api_orch_config_save(body: dict) -> dict:
    if not isinstance(body, dict):
        return {"ok": False, "error": "bad body"}
    cfg = load_config()
    for k in ("plannerAssignee", "aggregatorAssignee"):
        v = body.get(k)
        if isinstance(v, str) and v.strip():
            cfg[k] = v.strip()
    if isinstance(body.get("defaultAssignees"), list):
        cfg["defaultAssignees"] = [str(a).strip() for a in body["defaultAssignees"]
                                   if str(a).strip()] or cfg["defaultAssignees"]
    if "maxParallel" in body:
        try:
            cfg["maxParallel"] = max(1, min(int(body["maxParallel"]), 16))
        except Exception:
            pass
    if "channelDebounceMs" in body:
        try:
            cfg["channelDebounceMs"] = max(0, int(body["channelDebounceMs"]))
        except Exception:
            pass
    if isinstance(body.get("bindings"), list):
        cfg["bindings"] = [b for b in (_sanitize_binding(x) for x in body["bindings"])
                           if b]
    if not save_config(cfg):
        return {"ok": False, "error": "save failed"}
    return {"ok": True, "config": load_config()}


def api_orch_bind(body: dict) -> dict:
    """Add or update a single binding."""
    cfg = load_config()
    new_b = _sanitize_binding(body or {})
    if not new_b:
        return {"ok": False, "error": "invalid binding"}
    bindings = cfg.get("bindings") or []
    # Replace existing match by (kind, channel/chat)
    key_field = "channel" if new_b["kind"] in ("slack", "http") else "chat"
    bindings = [b for b in bindings
                if not (b.get("kind") == new_b["kind"]
                        and b.get(key_field) == new_b.get(key_field))]
    bindings.append(new_b)
    cfg["bindings"] = bindings
    if not save_config(cfg):
        return {"ok": False, "error": "save failed"}
    return {"ok": True, "binding": new_b, "bindings": bindings}


def api_orch_unbind(body: dict) -> dict:
    cfg = load_config()
    kind = (body.get("kind") or "").strip().lower()
    target = (body.get("channel") or body.get("chat") or "").strip()
    if not kind or not target:
        return {"ok": False, "error": "kind and channel/chat required"}
    field = "channel" if kind in ("slack", "http") else "chat"
    cfg["bindings"] = [b for b in (cfg.get("bindings") or [])
                       if not (b.get("kind") == kind and b.get(field) == target)]
    if not save_config(cfg):
        return {"ok": False, "error": "save failed"}
    return {"ok": True, "bindings": cfg["bindings"]}


def api_orch_dispatch(body: dict) -> dict:
    """POST /api/orchestrator/dispatch — synchronous run, returns final result.

    For UI use: lets you run the orchestrator without a chat platform attached.
    """
    if not isinstance(body, dict):
        return {"ok": False, "error": "bad body"}
    text = (body.get("text") or "").strip()
    if not text:
        return {"ok": False, "error": "text required"}
    return dispatch(
        text,
        kind=(body.get("kind") or "http"),
        channel=(body.get("channel") or "default"),
        user=(body.get("user") or ""),
    )


def api_orch_start(body: dict | None = None) -> dict:
    return {"ok": True, "status": start_listeners()}


def api_orch_history(query: dict | None = None) -> dict:
    """GET /api/orchestrator/history?limit=50"""
    limit = 50
    if isinstance(query, dict):
        v = query.get("limit")
        if isinstance(v, list):
            v = v[0] if v else 50
        try:
            limit = int(v or 50)
        except (TypeError, ValueError):
            limit = 50
    return {"ok": True, "runs": list_run_history(limit)}


def api_orch_history_get(query: dict | None = None) -> dict:
    """GET /api/orchestrator/history/get?runId=..."""
    rid = ""
    if isinstance(query, dict):
        v = query.get("runId")
        if isinstance(v, list):
            v = v[0] if v else ""
        rid = str(v or "")
    if not rid:
        return {"ok": False, "error": "runId required"}
    rec = get_run_record(rid)
    if not rec:
        return {"ok": False, "error": "not found"}
    return {"ok": True, "run": rec}


def _q_str(query: dict | None, key: str, default: str = "") -> str:
    if not isinstance(query, dict):
        return default
    v = query.get(key)
    if isinstance(v, list):
        v = v[0] if v else default
    return str(v or default)


def _q_int(query: dict | None, key: str, default: int) -> int:
    if not isinstance(query, dict):
        return default
    v = query.get(key)
    if isinstance(v, list):
        v = v[0] if v else default
    try:
        return int(v or default)
    except (TypeError, ValueError):
        return default


def api_orch_inbound(query: dict | None = None) -> dict:
    """GET /api/orchestrator/inbound?kind=&channel=&since=&limit="""
    return {"ok": True, "items": list_inbound(
        kind=_q_str(query, "kind"),
        channel=_q_str(query, "channel"),
        since_id=_q_int(query, "since", 0),
        limit=_q_int(query, "limit", 100),
    )}


def api_orch_outbound(query: dict | None = None) -> dict:
    """GET /api/orchestrator/outbound?kind=&channel=&runId=&since=&limit="""
    return {"ok": True, "items": list_outbound(
        kind=_q_str(query, "kind"),
        channel=_q_str(query, "channel"),
        run_id=_q_str(query, "runId"),
        since_id=_q_int(query, "since", 0),
        limit=_q_int(query, "limit", 100),
    )}


def _verify_slack_signature(raw_body: bytes, headers: dict, secret: str,
                            now_s: Optional[float] = None) -> tuple[bool, str]:
    """HMAC-SHA256 over ``v0:<ts>:<body>``. Slack rotates timestamps on each
    request; reject anything more than 5 minutes off the wall clock to
    foreclose replay attacks.

    Returns ``(ok, reason)``. The reason is for logs only — never send the
    detail back to the client (no oracle).
    """
    import hmac
    ts = headers.get("X-Slack-Request-Timestamp") or headers.get("x-slack-request-timestamp") or ""
    sig = headers.get("X-Slack-Signature") or headers.get("x-slack-signature") or ""
    if not (ts and sig):
        return False, "missing-headers"
    try:
        ts_int = int(ts)
    except ValueError:
        return False, "bad-timestamp"
    if abs((now_s if now_s is not None else time.time()) - ts_int) > 300:
        return False, "stale-timestamp"
    base = f"v0:{ts}:".encode("utf-8") + (raw_body or b"")
    expected = "v0=" + hmac.new(secret.encode("utf-8"), base, "sha256").hexdigest()
    if not hmac.compare_digest(expected, sig):
        return False, "signature-mismatch"
    return True, "ok"


def handle_slack_events_request(handler) -> None:
    """Custom HTTP handler for ``POST /api/slack/events`` so we can read the
    raw body for HMAC verification *before* JSON parsing.

    Wired in ``server.routes.do_POST`` as a special-case path.
    """
    length = 0
    try:
        length = int(handler.headers.get("Content-Length", 0) or 0)
    except (TypeError, ValueError):
        length = 0
    raw = handler.rfile.read(length) if length else b""

    secret = os.environ.get("SLACK_SIGNING_SECRET", "").strip()
    if secret:
        ok, reason = _verify_slack_signature(raw, dict(handler.headers), secret)
        if not ok:
            log.warning("slack signature verification failed: %s", reason)
            handler.send_response(401)
            handler.send_header("Content-Type", "application/json")
            handler.end_headers()
            handler.wfile.write(b'{"ok":false,"error":"unauthorized"}')
            return

    try:
        body = json.loads(raw.decode("utf-8")) if raw else {}
    except Exception:
        body = {}
    if not isinstance(body, dict):
        body = {}

    if body.get("type") == "url_verification":
        handler.send_response(200)
        handler.send_header("Content-Type", "application/json")
        handler.end_headers()
        handler.wfile.write(json.dumps({"challenge": body.get("challenge", "")}).encode("utf-8"))
        return

    handle_slack_event(body)
    handler.send_response(200)
    handler.send_header("Content-Type", "application/json")
    handler.end_headers()
    handler.wfile.write(b'{"ok":true}')


def api_slack_events(body: dict) -> dict:
    """JSON-only fallback handler. Used by the dispatcher for routes that
    bypass ``handle_slack_events_request`` (e.g. tests). Production traffic
    goes through the raw-body handler above.
    """
    if not isinstance(body, dict):
        return {"ok": False, "error": "bad body"}
    if body.get("type") == "url_verification":
        return {"challenge": body.get("challenge", "")}
    handle_slack_event(body)
    return {"ok": True}


def api_telegram_webhook(body: dict) -> dict:
    """POST /api/telegram/webhook — webhook-mode receiver (alternative to long-poll)."""
    if not isinstance(body, dict):
        return {"ok": False, "error": "bad body"}
    handle_telegram_update(body)
    return {"ok": True}


def handle_discord_interactions_request(handler) -> None:
    """Custom HTTP handler for ``POST /api/discord/interactions``.

    Reads the raw body, verifies the ed25519 signature using the configured
    publicKey (Discord requires this on every interaction), then dispatches
    via ``handle_discord_interaction``. Always returns JSON.
    """
    from . import discord_api

    length = 0
    try:
        length = int(handler.headers.get("Content-Length", 0) or 0)
    except (TypeError, ValueError):
        length = 0
    raw = handler.rfile.read(length) if length else b""

    sig = (handler.headers.get("X-Signature-Ed25519") or "")
    ts  = (handler.headers.get("X-Signature-Timestamp") or "")
    cfg = discord_api.load_discord_config()
    pk_hex = cfg.get("publicKey", "")

    if not pk_hex:
        log.warning("discord interactions: no publicKey configured — rejecting")
        handler.send_response(401)
        handler.send_header("Content-Type", "application/json")
        handler.end_headers()
        handler.wfile.write(b'{"error":"publicKey not configured"}')
        return

    if not discord_api.verify_interaction_signature(raw, sig, ts, pk_hex):
        handler.send_response(401)
        handler.send_header("Content-Type", "application/json")
        handler.end_headers()
        handler.wfile.write(b'{"error":"invalid request signature"}')
        return

    try:
        payload = json.loads(raw.decode("utf-8")) if raw else {}
    except Exception:
        payload = {}
    if not isinstance(payload, dict):
        payload = {}

    response = handle_discord_interaction(payload)
    handler.send_response(200)
    handler.send_header("Content-Type", "application/json")
    handler.end_headers()
    handler.wfile.write(json.dumps(response, ensure_ascii=False).encode("utf-8"))
