#!/usr/bin/env python3
"""Auto-Resume Haiku summary helper — direct Anthropic Messages API.

Reads the tail of a Claude Code session jsonl transcript, asks Haiku 4.5
to summarise it for context handoff, and prints the summary to stdout.

Designed to be invoked from the Stop-hook bash script generated by
`server/auto_resume_hooks.py` when the user opts into the direct-API
backend. On any failure the script prints an empty stdout and exits
non-zero so the caller can fall back to raw-tail-only mode.

Stdlib only — no third-party imports.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

API_URL = "https://api.anthropic.com/v1/messages"
API_VERSION = "2023-06-01"
MODEL = "claude-haiku-4-5-20251001"
MAX_TOKENS = 200
TIMEOUT_SECONDS = 10
DEFAULT_TAIL_BYTES = 16384

PROMPT_TEMPLATE = (
    "Summarize this Claude Code session in 2-3 sentences for context "
    "handoff. Focus on: the user's task, what was completed, and the "
    "immediate next step.\n\nConversation tail:\n\n{tail}"
)


def _resolve_api_key() -> str:
    """Return the Anthropic API key from env or the lazyclaude store."""
    env_key = os.environ.get("ANTHROPIC_API_KEY", "").strip()
    if env_key:
        return env_key

    # Fallback: lazyclaude provider store. Schema is shared with
    # server/ai_providers.py — top-level may be either a list of
    # providers or a dict with a "providers" array. Tolerate both.
    store_path = Path.home() / ".claude-dashboard-ai-providers.json"
    if not store_path.is_file():
        return ""
    try:
        data = json.loads(store_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return ""

    if isinstance(data, dict):
        candidates = data.get("providers") or []
    elif isinstance(data, list):
        candidates = data
    else:
        candidates = []

    if not isinstance(candidates, list):
        return ""

    for entry in candidates:
        if not isinstance(entry, dict):
            continue
        provider = str(entry.get("provider") or entry.get("id") or "").lower()
        if "anthropic" in provider or provider == "claude":
            key = entry.get("apiKey") or entry.get("api_key") or ""
            if isinstance(key, str) and key.strip():
                return key.strip()
    return ""


def _read_tail(path: Path, tail_bytes: int) -> str:
    """Read the last `tail_bytes` of `path` as UTF-8 (errors replaced)."""
    if not path.is_file():
        return ""
    size = path.stat().st_size
    if size == 0:
        return ""
    with path.open("rb") as f:
        if size > tail_bytes:
            f.seek(-tail_bytes, os.SEEK_END)
        blob = f.read()
    return blob.decode("utf-8", errors="replace")


def _build_request(api_key: str, prompt: str) -> tuple[str, dict, bytes]:
    """Return (url, headers, body) for the Messages API call."""
    headers = {
        "x-api-key": api_key,
        "anthropic-version": API_VERSION,
        "content-type": "application/json",
    }
    payload = {
        "model": MODEL,
        "max_tokens": MAX_TOKENS,
        "messages": [{"role": "user", "content": prompt}],
    }
    body = json.dumps(payload).encode("utf-8")
    return API_URL, headers, body


def _redact(headers: dict) -> dict:
    """Return a copy of headers with the API key masked for logging."""
    out = dict(headers)
    key = out.get("x-api-key", "")
    if key:
        out["x-api-key"] = key[:6] + "...REDACTED" if len(key) > 6 else "REDACTED"
    return out


def _call_api(url: str, headers: dict, body: bytes) -> str:
    """POST the request and return the assistant text."""
    req = urllib.request.Request(url, data=body, headers=headers, method="POST")
    with urllib.request.urlopen(req, timeout=TIMEOUT_SECONDS) as resp:
        raw = resp.read()
    data = json.loads(raw.decode("utf-8"))
    content = data.get("content") or []
    if not isinstance(content, list) or not content:
        raise ValueError("empty content in response")
    first = content[0]
    if not isinstance(first, dict):
        raise ValueError("malformed content[0]")
    text = first.get("text", "")
    if not isinstance(text, str):
        raise ValueError("content[0].text not a string")
    return text.strip()


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Summarise a Claude Code jsonl tail via the Anthropic Messages API.",
    )
    parser.add_argument(
        "--jsonl-path",
        required=True,
        help="Path to the session jsonl transcript.",
    )
    parser.add_argument(
        "--tail-bytes",
        type=int,
        default=DEFAULT_TAIL_BYTES,
        help=f"Bytes of trailing transcript to summarise (default: {DEFAULT_TAIL_BYTES}).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the planned request (key redacted) and exit without calling the API.",
    )
    args = parser.parse_args()

    jsonl = Path(args.jsonl_path).expanduser()
    tail = _read_tail(jsonl, max(1, int(args.tail_bytes)))
    if not tail:
        # Empty stdout, diagnostic on stderr, exit 1 — shell falls back.
        print("", end="")
        print(f"ar-haiku-summary: jsonl missing or empty: {jsonl}", file=sys.stderr)
        return 1

    prompt = PROMPT_TEMPLATE.format(tail=tail)
    api_key = _resolve_api_key()

    if args.dry_run:
        url, headers, body = _build_request(api_key or "MISSING", prompt)
        print(f"URL: {url}")
        print(f"Headers: {json.dumps(_redact(headers), indent=2)}")
        print(f"Body: {body.decode('utf-8')}")
        return 0

    if not api_key:
        print("", end="")
        print("ar-haiku-summary: no ANTHROPIC_API_KEY in env or provider store", file=sys.stderr)
        return 2

    url, headers, body = _build_request(api_key, prompt)
    try:
        text = _call_api(url, headers, body)
    except urllib.error.HTTPError as e:
        print("", end="")
        print(f"ar-haiku-summary: HTTP {e.code}: {e.reason}", file=sys.stderr)
        return 3
    except urllib.error.URLError as e:
        print("", end="")
        print(f"ar-haiku-summary: network error: {e.reason}", file=sys.stderr)
        return 4
    except (ValueError, json.JSONDecodeError) as e:
        print("", end="")
        print(f"ar-haiku-summary: parse error: {e}", file=sys.stderr)
        return 5
    except Exception as e:  # noqa: BLE001 — last-resort net so shell fallback fires
        print("", end="")
        print(f"ar-haiku-summary: unexpected error: {e}", file=sys.stderr)
        return 6

    print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
